spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always

naver:
  url: https://openapi.naver.com/v1/search/book.json
  client-key: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}
