spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/book_bti_test
    username: sa
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true

naver:
  url: https://openapi.naver.com/v1/search/book.json
  client-key: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}
